# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  install:
    desc: Run install script
    cmds:
      - ./bin/install.mac.sh
    silent: true

  fmt:
    desc: Format nvim Lua files
    dir: .config/nvim
    cmds:
      - stylua .

  lint:
    desc: Lint nvim Lua files
    dir: .config/nvim
    cmds:
      - stylua --check .
      - luacheck .
      - lua-language-server --check .
